### ISSUE TITLE
Existing search not working correctly!

### ISSUE THREAD

**Issue by palvitgarg99** [elric97/feature-hunt#12]
Exisitng search logic is not able to search all keywords correctly.
For instance fo searching in tag, different case can lead to diferent results.
Also there is no searching in description either. It is very rare that someone can find required idea from tags and name alone.

**Comment by palvitgarg99** [comment]
PR: https://github.com/elric97/feature-hunt/pull/14
Under review!

**Comment by elric97** [comment]
PR merged, closing this
