### ISSUE TITLE
Search architecture design is inappropriate!

### ISSUE THREAD

**Issue by palvitgarg99** [elric97/feature-hunt#13]
The search for any keyword happens at front end as per current code. But this will cause very big delays when db size grows.
Instead, we should restrict search from db itself. Only get those documents from db which match with our query.

Implement search logic in backend server and send only appropriate documents to front end.

**Comment by palvitgarg99** [comment]
PR: https://github.com/elric97/feature-hunt/pull/14

**Comment by elric97** [comment]
LGTM, make sure all the pre-checks are passing before merging.

**Comment by palvitgarg99** [comment]
All pre-checks are passing. Change is merged and working fine.
