### ISSUE TITLE
Incorrect routing while clicking any feature idea on home page

### ISSUE THREAD

**Issue by palvitgarg99** [elric97/feature-hunt#16]
![image](https://user-images.githubusercontent.com/16212546/143726057-a1b978a9-34c5-4bb3-b109-7085b81eb0c8.png)

**Comment by palvitgarg99** [comment]
PR: https://github.com/elric97/feature-hunt/pull/14

**Comment by elric97** [comment]
Looks like the PR was merged, closing this issue now
