### ISSUE TITLE
Feature up vote breaks the UI

### ISSUE THREAD

**Issue by elric97** [elric97/feature-hunt#17]
<img width="727" alt="Screen Shot 2021-11-28 at 15 35 04" src="https://user-images.githubusercontent.com/17125417/143785010-4c25c280-248b-4f78-b38f-274cbebe589f.png">
<img width="716" alt="Screen Shot 2021-11-28 at 15 35 11" src="https://user-images.githubusercontent.com/17125417/143785011-49838dd6-61d6-40c5-a6ae-5f75e62955e7.png">

**Comment by aditi12200** [comment]
This bug has been fixed. It is working correctly now.

**Comment by elric97** [comment]
Closing
