### ISSUE TITLE
Add phase 3 improvement doc

### ISSUE THREAD

**Issue by elric97** [elric97/feature-hunt#21]

**Comment by elric97** [comment]
@ShreeSub please make sure this gets created by today EOD.

**Comment by ShreeSub** [comment]
Currently working on it

**Comment by ShreeSub** [comment]
I have updated the [DeltaDocument.md](https://github.com/elric97/feature-hunt/blob/main/Phase_3_Docs/deltaDocument.md) please have a look @elric97
